name: CI Trigger

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Frontend CI
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs');
            fs.writeFileSync('.github/workflows/frontend-ci-trigger.txt', 'trigger frontend');

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Backend CI
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs');
            fs.writeFileSync('.github/workflows/backend-ci-trigger.txt', 'trigger backend');
