name: Main CI Trigger

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger frontend CI
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');

            // Trigger frontend CI workflow
            fs.writeFileSync('.github/workflows/frontend-ci-trigger.txt', '');
